[phases.setup]
nixPkgs = [
    'glib',
    'nss',
    'nspr',
    'atk',
    'cups',
    'dbus',
    'libdrm',
    'libxkbcommon',
    'libatspi',
    'pango',
    'cairo',
    'alsa-lib',
    'expat',
    'fontconfig',
    'freetype',
    'gdk-pixbuf',
    'gtk3',
    'libX11',
    'libXcomposite',
    'libXcursor',
    'libXdamage',
    'libXext',
    'libXfixes',
    'libXi',
    'libXrandr',
    'libXrender',
    'libXScrnSaver',
    'libXtst',
    'pciutils',
    'xorg-server',
    'xvfb',
    'libgbm'
]